// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqkY_jDwp4W-3JhyjMdhukX50ehHkDuNg',
    appId: '1:1076798630058:android:8d0ff084ca1a11e9a788d3',
    messagingSenderId: '1076798630058',
    projectId: 'renttie-app',
    storageBucket: 'renttie-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHjhHT_yviyI08i0u65TkzUj2NcNzwxeU',
    appId: '1:1076798630058:ios:414feaada81823a4a788d3',
    messagingSenderId: '1076798630058',
    projectId: 'renttie-app',
    storageBucket: 'renttie-app.firebasestorage.app',
    iosBundleId: 'com.example.renttie',
  );
}
